name: Django CI/CD for delivery
on:
  push:
    branches: ['main', 'delivery']
  pull_request:
    branches: ['main', 'delivery']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install flake8
      - name: Test with flake8
        run: |
            cd backend/delivery && python -m flake8
      - name: Build and run containers
        run: |
            cd backend/delivery && docker-compose up -d --build